### ISSUE TITLE
questions related to DB deletion and indexing

### ISSUE THREAD

**Issue by TakahiroHaruyama** [McGill-DMaS/Kam1n0-Plugin-IDA-Pro#21]
1. How can we delete sample DB from Binary Browser? I checked the tutorials but could not find that.

2. Is there any method to index existing multiple idbs? I'd like to use existing idbs with renamed functions for indexing, not to use newly-generated ones by the server. In that case do I have to open each idb on IDA then index all functions manually?

Thanks,
Takahiro

**Comment by steven-hh-ding** [comment]
Hi Takahiro,

Thank you for your interest in our research. You can directly index your existing idb files instead of the binary file.  All types of comments will be imported as well. The deletion interface is not implemented yet; since we are still trying to figure out how to partially remove the index nice and clean. For now you can filter out the results. 

Best,

Steven

**Comment by TakahiroHaruyama** [comment]
Hi Steven,

Thank you so much for answering questions!
I think the tool is very unique because other binary diffing tools just compare one to one binary. I hope you keep the cool work.

Thanks,
Takahiro

**Comment by steven-hh-ding** [comment]
Thank you Takahiro. We also very much value your feedback. More new apps are coming later this year, with improvements to the existing one as well. Please feel free to open any new issue. I am closing this thread for now.
